#!/bin/bash -xe

mkcamlp5.opt pa_r.cmx pa_rp.cmx pr_dump.cmx pa_lexer.cmx pa_extend.cmx q_MLast.cmx pa_reloc.cmx pa_macro.cmx -o syntax0
hol=/usr/local/google/home/geoffreyi/ocaml/hol-light
mkcamlp5.opt -pp $hol/syntax0 pa_r.cmx pa_rp.cmx pr_dump.cmx pa_lexer.cmx pa_extend.cmx q_MLast.cmx pa_reloc.cmx pa_macro.cmx pa_j_tweak.ml -I `camlp5 -where` -o syntax1
mkcamlp5.opt -pp $hol/syntax1 nums.cmxa pa_r.cmx pa_rp.cmx pr_dump.cmx pa_lexer.cmx pa_extend.cmx q_MLast.cmx pa_reloc.cmx pa_macro.cmx pa_j_tweak.cmx system.ml -I `camlp5 -where` -o syntax2

holsrc='hol_native.ml system.ml lib.ml fusion.ml basics.ml nets.ml printer.ml preterm.ml parser.ml equal.ml bool.ml drule.ml tactics.ml itab.ml simp.ml theorems.ml ind_defs.ml class.ml trivia.ml canon.ml meson.ml metis.ml quot.ml impconv.ml pair.ml nums.ml recursion.ml arith.ml wf.ml calc_num.ml normalizer.ml grobner.ml ind_types.ml lists.ml realax.ml calc_int.ml realarith.ml reals.ml calc_rat.ml ints.ml sets.ml iterate.ml cart.ml define.ml help.ml database.ml'

./native-rewrite $holsrc
ocamlopt.opt -pp $hol/syntax2 nums.cmxa quotation.cmx $holsrc -I `camlp5 -where` -o victory
